import React, { FC } from 'react';
import Head from "next/head";

interface Props {
    children: React.ReactNode;
}

export const AppLayout:FC<Props> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Exchange Rate Calculator</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                { children }
            </main>
        </>
    )
}



