// Generated by https://quicktype.io

export interface Symbol {
    [key: string]: string;
}

export interface Currencies {
    success: boolean;
    symbols: Symbol;
}

export interface ConvertResultAPI {
    date:       string;
    historical: string;
    info:       Info;
    query:      Query;
    result:     number;
    success:    boolean;
}

export interface Info {
    rate:      number;
    timestamp: number;
}

export interface Query {
    amount: number;
    from:   string;
    to:     string;
}
